### //check the first http request

GET http://localhost:3000/

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Post1",
    "content": "First Post",
    "sender": "Amit",
    "senderId": "123456"
}

##

GET http://localhost:3000/posts/673a41f3942bde2829549778

##