
###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Post1",
    "content": "First Post",
    "sender": "Amit",
    "senderId": "123456"
}

###
GET http://localhost:3000/posts

###
GET http://localhost:3000/posts?senderId=123456
